export type PromptType = "binary" | "multiple_choice" | "scale";
export type Prompt = {
  id: string;
  text: string;
  type: PromptType;
  options?: string[];
  labelLow?: string;
  labelHigh?: string;
};

export type QuestionBank = "general" | "coworkers" | "hotseat";

export const BANK_META: Record<QuestionBank, { label: string; emoji: string; description: string }> = {
  general:   { label: "General",   emoji: "🎲", description: "A mix of everything" },
  coworkers: { label: "Coworkers", emoji: "💼", description: "Work-safe, office-friendly" },
  hotseat:   { label: "Hot Seat",  emoji: "🌶️", description: "Spicy — not for the faint of heart" },
};

const GENERAL_PROMPTS: Prompt[] = [
  // Binary
  { id: "b1",  text: "Are you the best driver in this room?", type: "binary" },
  { id: "b2",  text: "Are you the best singer in this room?", type: "binary" },
  { id: "b3",  text: "Are you usually the one who kills the vibe?", type: "binary" },
  { id: "b4",  text: "Can you have an opposite-sex best friend in a relationship?", type: "binary" },
  { id: "b5",  text: "Can you ride a bike?", type: "binary" },
  { id: "b6",  text: "Can you run a half marathon?", type: "binary" },
  { id: "b7",  text: "Can you separate the art from the artist?", type: "binary" },
  { id: "b8",  text: "Can you swim?", type: "binary" },
  { id: "b9",  text: "Did you have a glow-up after high school?", type: "binary" },
  { id: "b10", text: "Did you learn piano as a kid?", type: "binary" },
  { id: "b11", text: "Do you believe in love at first sight?", type: "binary" },
  { id: "b12", text: "Do you believe in manifestation?", type: "binary" },
  { id: "b13", text: "Do you consider yourself a morning person?", type: "binary" },
  { id: "b14", text: "Do you cry at weddings?", type: "binary" },
  { id: "b15", text: "Do you make your bed every morning?", type: "binary" },
  { id: "b16", text: "Do you still talk to your first love?", type: "binary" },
  { id: "b17", text: "Do you think men should always pay for the first date?", type: "binary" },
  { id: "b18", text: "Do you think money can buy happiness?", type: "binary" },
  { id: "b19", text: "Do you think you are above average intelligence?", type: "binary" },
  { id: "b20", text: "Do you think you are a good cook?", type: "binary" },
  { id: "b21", text: "Do you think you can date someone vegetarian?", type: "binary" },
  { id: "b22", text: "Do you think you could go vegan for a month?", type: "binary" },
  { id: "b23", text: "Do you think you could live without social media for a year?", type: "binary" },
  { id: "b24", text: "Do you think you could survive a week with no phone?", type: "binary" },
  { id: "b25", text: "Do you think you could win a trivia night?", type: "binary" },
  { id: "b26", text: "Do you wash your legs in the shower?", type: "binary" },
  { id: "b27", text: "Have you been on a Hinge date?", type: "binary" },
  { id: "b28", text: "Have you ever asked someone out in public?", type: "binary" },
  { id: "b29", text: "Have you ever been dumped by text?", type: "binary" },
  { id: "b30", text: "Have you ever been in a physical fight?", type: "binary" },
  { id: "b31", text: "Have you ever been on a blind date?", type: "binary" },
  { id: "b32", text: "Have you ever blocked someone on social media and then checked their profile anyway?", type: "binary" },
  { id: "b33", text: "Have you ever cheated on a test or exam?", type: "binary" },
  { id: "b34", text: "Have you ever cried at a movie in public?", type: "binary" },
  { id: "b35", text: "Have you ever drunk-texted an ex?", type: "binary" },
  { id: "b36", text: "Have you ever ghosted someone you were dating?", type: "binary" },
  { id: "b37", text: "Have you ever kissed the opposite sex?", type: "binary" },
  { id: "b38", text: "Have you ever lied on your resume?", type: "binary" },
  { id: "b39", text: "Have you ever missed a flight that was your fault?", type: "binary" },
  { id: "b40", text: "Have you ever permed or dyed your hair?", type: "binary" },
  { id: "b41", text: "Have you ever pretended to be sick to avoid plans?", type: "binary" },
  { id: "b42", text: "Have you ever pulled an all-nighter this year?", type: "binary" },
  { id: "b43", text: "Have you ever re-read your own old texts and cringed?", type: "binary" },
  { id: "b44", text: "Have you ever shown up to something overdressed?", type: "binary" },
  { id: "b45", text: "Have you ever slept over on the first date?", type: "binary" },
  { id: "b46", text: "Have you ever slid into someone's DMs and gotten a response?", type: "binary" },
  { id: "b47", text: "Have you ever stalked an ex's new partner on social media?", type: "binary" },
  { id: "b48", text: "Have you ever stolen from a retail store?", type: "binary" },
  { id: "b49", text: "Have you ever walked out of a movie?", type: "binary" },
  { id: "b50", text: "Have you said 'I love you' first in a relationship?", type: "binary" },
  { id: "b51", text: "Is there a song that makes you cry every time?", type: "binary" },
  { id: "b52", text: "Would you move to a different country for a partner?", type: "binary" },
  { id: "b53", text: "Would you rather be famous than rich?", type: "binary" },
  { id: "b54", text: "Would you take your ex back if they asked right now?", type: "binary" },
  { id: "b55", text: "Would you tell a friend if their partner was cheating?", type: "binary" },
  { id: "b56", text: "Would you text someone you like first without a reason?", type: "binary" },
  { id: "b57", text: "Would you turn down a dream job if it meant moving cities?", type: "binary" },
  { id: "b58", text: "Would you use a dating app right now if you were single?", type: "binary" },
  { id: "b59", text: "Would you go skydiving if someone paid for it?", type: "binary" },
  { id: "b60", text: "Would you rather know if your friends talk badly about you?", type: "binary" },

  // Multiple Choice
  { id: "mc1",  text: "Biggest social media red flag in a potential partner?", type: "multiple_choice", options: ["No photos", "Only selfies", "Following too many models", "Cryptic captions"] },
  { id: "mc2",  text: "How do you handle conflict?", type: "multiple_choice", options: ["Address it head-on", "Avoid it entirely", "Passive-aggressive hints", "Vent to a friend first"] },
  { id: "mc3",  text: "How do you usually end a relationship?", type: "multiple_choice", options: ["Honest conversation", "Slow fade", "Ghosting", "Never have"] },
  { id: "mc4",  text: "How do you feel about pineapple on pizza?", type: "multiple_choice", options: ["Love it", "Hate it", "Don't care", "Depends on the pizza"] },
  { id: "mc5",  text: "How many kids do you want?", type: "multiple_choice", options: ["0", "1", "2", "3+"] },
  { id: "mc6",  text: "How often do you cry?", type: "multiple_choice", options: ["Never", "Once a blue moon", "Several times a year", "It happens"] },
  { id: "mc7",  text: "How punctual are you?", type: "multiple_choice", options: ["Always early", "Right on time", "A little late", "Fashionably late always"] },
  { id: "mc8",  text: "How would you rather spend a free Saturday?", type: "multiple_choice", options: ["Hiking outdoors", "Brunching with friends", "Gaming or Netflix", "Exploring a new city"] },
  { id: "mc9",  text: "If you could only eat one breakfast forever, what is it?", type: "multiple_choice", options: ["Eggs and toast", "Açaí bowl", "Nothing, I skip it", "Whatever's closest"] },
  { id: "mc10", text: "Most physically attractive facial feature?", type: "multiple_choice", options: ["Hair", "Nose", "Eyes", "Mouth"] },
  { id: "mc11", text: "Pick your vibe this week.", type: "multiple_choice", options: ["Thriving", "Surviving", "Barely functioning", "On another planet"] },
  { id: "mc12", text: "Stuck listening to 1 song on repeat all day. Pick one.", type: "multiple_choice", options: ["Baby", "All I Want For Christmas", "Thunder", "Despacito"] },
  { id: "mc13", text: "What career would you choose if they paid the same?", type: "multiple_choice", options: ["Doctor", "Pilot", "Bar bouncer", "TSA Agent"] },
  { id: "mc14", text: "What country would you spend a week in?", type: "multiple_choice", options: ["Bolivia", "Cape Town", "Poland", "Kyrgyzstan"] },
  { id: "mc15", text: "What is your ideal Sunday?", type: "multiple_choice", options: ["Brunch and errands", "Full reset and self-care", "Outdoor adventure", "Doing absolutely nothing"] },
  { id: "mc16", text: "What kind of drunk are you?", type: "multiple_choice", options: ["Party", "Affectionate", "Gossiping", "Chilled out"] },
  { id: "mc17", text: "What kind of traveler are you?", type: "multiple_choice", options: ["Over-planner", "Wing it", "Only luxury", "Budget backpacker"] },
  { id: "mc18", text: "What type of movie do you most relate to your life?", type: "multiple_choice", options: ["Rom-com", "Horror", "Action", "Documentary"] },
  { id: "mc19", text: "What would you do in the zombie apocalypse?", type: "multiple_choice", options: ["Form a group and lead", "Hide alone", "Find the cure", "Accept my fate"] },
  { id: "mc20", text: "What would you do with an unexpected $10,000?", type: "multiple_choice", options: ["Invest it", "Travel", "Pay off debt", "Spend it immediately"] },
  { id: "mc21", text: "What would your friends say is your biggest flaw?", type: "multiple_choice", options: ["Too stubborn", "Too flaky", "Too blunt", "Too sensitive"] },
  { id: "mc22", text: "What's the minimum you'd take to be vegetarian for a year?", type: "multiple_choice", options: ["$1,000", "$10,000", "$100,000", "$1,000,000"] },
  { id: "mc23", text: "What's your favorite season?", type: "multiple_choice", options: ["Winter", "Spring", "Summer", "Fall"] },
  { id: "mc24", text: "What's your go-to drunk food?", type: "multiple_choice", options: ["Pizza", "Fries", "Ramen", "Kebab"] },
  { id: "mc25", text: "What's your go-to karaoke song type?", type: "multiple_choice", options: ["90s banger", "Emotional ballad", "Rap", "Whatever gets the crowd going"] },
  { id: "mc26", text: "What's your ideal vacation vibe?", type: "multiple_choice", options: ["Nature and hiking", "Historic towns", "Urban city", "Beachy resort"] },
  { id: "mc27", text: "What's your love language?", type: "multiple_choice", options: ["Words of affirmation", "Acts of service", "Gift giving", "Physical touch"] },
  { id: "mc28", text: "What's your texting style?", type: "multiple_choice", options: ["Reply ASAP", "Check once in a while", "Respond to everyone at once", "I'm always Do Not Disturb"] },
  { id: "mc29", text: "When you get home after a long day, what's first?", type: "multiple_choice", options: ["Change clothes immediately", "Check my phone", "Eat something", "Lie down and stare at the ceiling"] },
  { id: "mc30", text: "Which career would stress you out the most?", type: "multiple_choice", options: ["ER doctor", "Air traffic controller", "High school teacher", "Debt collector"] },
  { id: "mc31", text: "Which cuisine would you eat exclusively for a year?", type: "multiple_choice", options: ["Indian", "Mexican", "Italian", "Greek"] },
  { id: "mc32", text: "Which describes your relationship with the gym?", type: "multiple_choice", options: ["I live there", "I go sometimes", "I pay but don't go", "What gym?"] },
  { id: "mc33", text: "Which era would you most want to live in?", type: "multiple_choice", options: ["1920s", "1970s", "1990s", "Far future"] },
  { id: "mc34", text: "Which is the worst way to be woken up?", type: "multiple_choice", options: ["Loud alarm", "Someone shaking you", "Bright lights", "A phone call"] },
  { id: "mc35", text: "Which pet would you own if you had to?", type: "multiple_choice", options: ["Dog", "Cat", "Bird", "Reptile"] },
  { id: "mc36", text: "Which protein would you eliminate for the rest of your life?", type: "multiple_choice", options: ["Chicken", "Beef", "Pork", "Fish"] },
  { id: "mc37", text: "Which skill would you most want to master overnight?", type: "multiple_choice", options: ["A new language", "An instrument", "Cooking", "A sport"] },
  { id: "mc38", text: "Which superpower would you pick?", type: "multiple_choice", options: ["Flight", "Invisibility", "Mind reading", "Teleportation"] },
  { id: "mc39", text: "Which would be the hardest to give up for a month?", type: "multiple_choice", options: ["Coffee", "Alcohol", "Junk food", "Your phone"] },
  { id: "mc40", text: "Which would stress you out most?", type: "multiple_choice", options: ["Public speaking", "Job interview", "First date", "Meeting the parents"] },
  { id: "mc41", text: "Which would you prefer to take on in a fight?", type: "multiple_choice", options: ["1 kangaroo", "3 wolves", "10 monkeys", "100 geese"] },
  { id: "mc42", text: "Which would you rather give up forever?", type: "multiple_choice", options: ["Social media", "Music", "Takeout food", "Streaming services"] },
  { id: "mc43", text: "Which finger would you choose if you had to lose one?", type: "multiple_choice", options: ["Ring", "Middle", "Index", "Thumb"] },
  { id: "mc44", text: "Which would you choose as a first date?", type: "multiple_choice", options: ["Movies", "Bar", "Lunch", "Activity"] },
  { id: "mc45", text: "Who do you call first when something goes wrong?", type: "multiple_choice", options: ["Mom or dad", "Best friend", "Partner", "I handle it alone"] },
  { id: "mc46", text: "Who in your life gives the best advice?", type: "multiple_choice", options: ["A parent", "A best friend", "Myself", "No one, I google it"] },
  { id: "mc47", text: "Your friend group needs a designated driver. Who actually does it?", type: "multiple_choice", options: ["Me, always", "We rotate", "Whoever drank least", "We just Uber"] },
  { id: "mc48", text: "Your ideal night out ends with what?", type: "multiple_choice", options: ["Late night food run", "Deep conversation somewhere quiet", "Dancing until close", "Home by midnight"] },
  { id: "mc49", text: "What's your go-to move when you can't sleep?", type: "multiple_choice", options: ["Scroll my phone", "Watch something", "Lie there suffering", "Get up and do something"] },
  { id: "mc50", text: "What's the most important quality in a best friend?", type: "multiple_choice", options: ["Loyalty", "Humor", "Honesty", "They just get it"] },
  { id: "mc51", text: "What's the first thing you notice about someone?", type: "multiple_choice", options: ["Their vibe", "Their looks", "How they treat others", "What they're wearing"] },
  { id: "mc52", text: "How do you take your coffee?", type: "multiple_choice", options: ["Black", "Milk and sugar", "Fancy espresso drink", "I don't drink coffee"] },
  { id: "mc53", text: "What's your go-to way to de-stress?", type: "multiple_choice", options: ["Exercise", "Eat something", "Watch TV", "Talk to someone"] },
  { id: "mc54", text: "What's your biggest money sin?", type: "multiple_choice", options: ["Eating out too much", "Impulse online shopping", "Subscriptions I forget about", "Never checking my balance"] },
  { id: "mc55", text: "What word describes your current situationship / relationship status best?", type: "multiple_choice", options: ["Thriving", "Complicated", "It's a long story", "Blissfully alone"] },
  { id: "mc56", text: "Which of these would you actually eat on a dare?", type: "multiple_choice", options: ["Bugs", "Raw fish", "Something from a trash can", "I would not"] },
  { id: "mc57", text: "Which decade had the best music?", type: "multiple_choice", options: ["70s", "80s", "90s", "2000s"] },
  { id: "mc58", text: "What's your most used app right now?", type: "multiple_choice", options: ["Instagram", "TikTok", "Spotify", "WhatsApp/iMessage"] },
  { id: "mc59", text: "What's your biggest pet peeve?", type: "multiple_choice", options: ["Loud chewing", "Being late", "Interrupting", "Vague texts"] },
  { id: "mc60", text: "How would you describe your sense of humor?", type: "multiple_choice", options: ["Dry and sarcastic", "Loud and chaotic", "Self-deprecating", "I'm the straight man"] },

  // Would You Rather (2 options)
  { id: "wyr1",  text: "Always 10 mins late or always 2 hours early?", type: "multiple_choice", options: ["Always 10 mins late", "Always 2 hours early"] },
  { id: "wyr2",  text: "Would you rather be always cold or always hot?", type: "multiple_choice", options: ["Always cold", "Always hot"] },
  { id: "wyr3",  text: "Would you rather be famous or be extremely rich?", type: "multiple_choice", options: ["Famous", "Extremely rich"] },
  { id: "wyr4",  text: "Would you rather be loved or respected?", type: "multiple_choice", options: ["Loved", "Respected"] },
  { id: "wyr5",  text: "Would you rather be the funniest or smartest in the room?", type: "multiple_choice", options: ["Funniest", "Smartest"] },
  { id: "wyr6",  text: "Would you rather fight one horse-sized duck or a hundred duck-sized horses?", type: "multiple_choice", options: ["One horse-sized duck", "100 duck-sized horses"] },
  { id: "wyr7",  text: "Would you rather fly or be invisible?", type: "multiple_choice", options: ["Fly", "Be invisible"] },
  { id: "wyr8",  text: "Would you rather give up texting or phone calls forever?", type: "multiple_choice", options: ["Give up texting", "Give up calls"] },
  { id: "wyr9",  text: "Would you rather have no phone or no car for a year?", type: "multiple_choice", options: ["No phone", "No car"] },
  { id: "wyr10", text: "Would you rather know when you'll die or how?", type: "multiple_choice", options: ["When", "How"] },
  { id: "wyr11", text: "Would you rather live 200 years ago or in the future?", type: "multiple_choice", options: ["200 years ago", "200 years in the future"] },
  { id: "wyr12", text: "Would you rather live in the city or countryside?", type: "multiple_choice", options: ["City", "Countryside"] },
  { id: "wyr13", text: "Would you rather lose your memories or your sight?", type: "multiple_choice", options: ["Lose memories", "Lose sight"] },
  { id: "wyr14", text: "Would you rather never sleep or never eat?", type: "multiple_choice", options: ["Never sleep", "Never eat"] },
  { id: "wyr15", text: "Would you rather only eat sweet or savory food?", type: "multiple_choice", options: ["Sweet only", "Savory only"] },
  { id: "wyr16", text: "Would you rather speak every language or play every instrument?", type: "multiple_choice", options: ["Speak every language", "Play every instrument"] },
  { id: "wyr17", text: "Would you rather always win or always get your way?", type: "multiple_choice", options: ["Always win arguments", "Always get your way"] },
  { id: "wyr18", text: "Would you rather always know when someone is lying or always get away with lying?", type: "multiple_choice", options: ["Know when others lie", "Always get away with it"] },
  { id: "wyr19", text: "Would you rather have your search history made public or your bank statements?", type: "multiple_choice", options: ["Search history", "Bank statements"] },
  { id: "wyr20", text: "Would you rather be the smartest person in the room or the most attractive?", type: "multiple_choice", options: ["Smartest", "Most attractive"] },
  { id: "wyr21", text: "Would you rather have no social media or no streaming services?", type: "multiple_choice", options: ["No social media", "No streaming"] },
  { id: "wyr22", text: "Would you rather go back to age 10 or fast forward to 60?", type: "multiple_choice", options: ["Back to 10", "Forward to 60"] },
  { id: "wyr23", text: "Would you rather only be able to whisper or only be able to shout?", type: "multiple_choice", options: ["Only whisper", "Only shout"] },
  { id: "wyr24", text: "Would you rather never be able to lie or never be able to keep a secret?", type: "multiple_choice", options: ["Can't lie", "Can't keep secrets"] },
  { id: "wyr25", text: "Would you rather have unlimited money or unlimited time?", type: "multiple_choice", options: ["Unlimited money", "Unlimited time"] },
  { id: "wyr26", text: "Would you rather live forever alone or live a short life surrounded by people you love?", type: "multiple_choice", options: ["Forever alone", "Short but surrounded"] },
  { id: "wyr27", text: "Would you rather always be overdressed or always be underdressed?", type: "multiple_choice", options: ["Always overdressed", "Always underdressed"] },
  { id: "wyr28", text: "Would you rather know all of your past lives or your future?", type: "multiple_choice", options: ["Past lives", "The future"] },
  { id: "wyr29", text: "Would you rather have a rewind button or a pause button for your life?", type: "multiple_choice", options: ["Rewind", "Pause"] },
  { id: "wyr30", text: "Would you rather always say what's on your mind or never be able to speak first?", type: "multiple_choice", options: ["Always speak your mind", "Never speak first"] },
  { id: "wyr31", text: "Would you rather be able to read minds or predict the future?", type: "multiple_choice", options: ["Read minds", "Predict the future"] },
  { id: "wyr32", text: "Would you rather have one true soulmate or 10 deep friendships?", type: "multiple_choice", options: ["One soulmate", "10 deep friendships"] },
  { id: "wyr33", text: "Would you rather give up alcohol or give up junk food forever?", type: "multiple_choice", options: ["Give up alcohol", "Give up junk food"] },
  { id: "wyr34", text: "Would you rather relive your worst memory or never dream again?", type: "multiple_choice", options: ["Relive worst memory", "Never dream again"] },
  { id: "wyr35", text: "Would you rather have your ex's password or have them have yours?", type: "multiple_choice", options: ["Have theirs", "They have mine"] },

  // Scale
  { id: "s1",  text: "Can you cook well?", type: "scale", labelLow: "Barely Edible", labelHigh: "Cheffing" },
  { id: "s2",  text: "Do you enjoy designer clothing?", type: "scale", labelLow: "Nope", labelHigh: "Definitely" },
  { id: "s3",  text: "Do you enjoy your job?", type: "scale", labelLow: "I Wanna Quit", labelHigh: "Amazing" },
  { id: "s4",  text: "Do you get sick often?", type: "scale", labelLow: "Never", labelHigh: "Too Often" },
  { id: "s5",  text: "Do you have a lot of free time?", type: "scale", labelLow: "Not At All", labelHigh: "Plenty" },
  { id: "s6",  text: "How adventurous are you with food?", type: "scale", labelLow: "Chicken Tenders Only", labelHigh: "Eat Anything" },
  { id: "s7",  text: "How close are you with your family?", type: "scale", labelLow: "Distant", labelHigh: "Extremely Close" },
  { id: "s8",  text: "How comfortable are you with confrontation?", type: "scale", labelLow: "Avoid At All Costs", labelHigh: "Bring It On" },
  { id: "s9",  text: "How competitive are you?", type: "scale", labelLow: "I Just Have Fun", labelHigh: "Must Win" },
  { id: "s10", text: "How deep is your current quarter-life crisis?", type: "scale", labelLow: "None At All", labelHigh: "Full Spiral" },
  { id: "s11", text: "How dramatic are you in a conflict?", type: "scale", labelLow: "Very Chill", labelHigh: "Full Reality Show" },
  { id: "s12", text: "How extroverted are you feeling today?", type: "scale", labelLow: "Total Hermit", labelHigh: "Social Butterfly" },
  { id: "s13", text: "How financially responsible are you right now?", type: "scale", labelLow: "Chaos", labelHigh: "On Lock" },
  { id: "s14", text: "How good are you at keeping secrets?", type: "scale", labelLow: "I'll Tell Everyone", labelHigh: "Fort Knox" },
  { id: "s15", text: "How hard do you go at karaoke?", type: "scale", labelLow: "I Watch", labelHigh: "Main Character" },
  { id: "s16", text: "How likely are you to flake on plans last minute?", type: "scale", labelLow: "Never", labelHigh: "Always" },
  { id: "s17", text: "How long can you go without checking your phone?", type: "scale", labelLow: "Under 5 Minutes", labelHigh: "Days Easily" },
  { id: "s18", text: "How materialistic are you?", type: "scale", labelLow: "Minimalist", labelHigh: "Love Nice Things" },
  { id: "s19", text: "How messy is your phone's camera roll right now?", type: "scale", labelLow: "Organized", labelHigh: "Total Chaos" },
  { id: "s20", text: "How messy is your room right now?", type: "scale", labelLow: "Spotless", labelHigh: "Disaster Zone" },
  { id: "s21", text: "How much do you care about what others think of you?", type: "scale", labelLow: "Not At All", labelHigh: "A Lot" },
  { id: "s22", text: "How much do you enjoy small talk?", type: "scale", labelLow: "Hate It", labelHigh: "Love It" },
  { id: "s23", text: "How much do you spend on going out per month?", type: "scale", labelLow: "Nothing", labelHigh: "Way Too Much" },
  { id: "s24", text: "How much do you trust your gut feelings?", type: "scale", labelLow: "Ignore Them", labelHigh: "Always Follow" },
  { id: "s25", text: "How much of a morning person are you?", type: "scale", labelLow: "Hate Mornings", labelHigh: "Love Them" },
  { id: "s26", text: "How much of a procrastinator are you?", type: "scale", labelLow: "Always Ahead", labelHigh: "Last Minute Always" },
  { id: "s27", text: "How much of a risk-taker are you in life?", type: "scale", labelLow: "Play It Safe", labelHigh: "All In" },
  { id: "s28", text: "How much do you rely on validation from others?", type: "scale", labelLow: "Not At All", labelHigh: "Constantly" },
  { id: "s29", text: "How often are you the last one awake at a gathering?", type: "scale", labelLow: "First To Bed", labelHigh: "Last One Standing" },
  { id: "s30", text: "How often are you the one to initiate plans with friends?", type: "scale", labelLow: "Never", labelHigh: "Always" },
  { id: "s31", text: "How often do you apologize first in an argument?", type: "scale", labelLow: "Never", labelHigh: "Always" },
  { id: "s32", text: "How often do you check your horoscope?", type: "scale", labelLow: "Never", labelHigh: "Daily" },
  { id: "s33", text: "How often do you exercise?", type: "scale", labelLow: "Never", labelHigh: "Every Day" },
  { id: "s34", text: "How often do you feel like you have your life together?", type: "scale", labelLow: "Never", labelHigh: "Totally" },
  { id: "s35", text: "How often do you follow through on New Year's resolutions?", type: "scale", labelLow: "Never", labelHigh: "Always" },
  { id: "s36", text: "How often do you overthink decisions?", type: "scale", labelLow: "Never", labelHigh: "Always" },
  { id: "s37", text: "How often do you romanticize your life?", type: "scale", labelLow: "Never", labelHigh: "All The Time" },
  { id: "s38", text: "How often do you text first?", type: "scale", labelLow: "Never", labelHigh: "Always" },
  { id: "s39", text: "How often do you unfollow people after an argument?", type: "scale", labelLow: "Never", labelHigh: "Immediately" },
  { id: "s40", text: "How petty can you be when someone wrongs you?", type: "scale", labelLow: "Saint", labelHigh: "Grudging" },
  { id: "s41", text: "How quickly do you catch feelings for someone?", type: "scale", labelLow: "Takes Forever", labelHigh: "Instantly" },
  { id: "s42", text: "How ready are you for a relationship right now?", type: "scale", labelLow: "Not At All", labelHigh: "Very Ready" },
  { id: "s43", text: "How spicy do you like your food?", type: "scale", labelLow: "No Spice", labelHigh: "Maximum Heat" },
  { id: "s44", text: "How well do you handle being ignored?", type: "scale", labelLow: "Unbothered", labelHigh: "Spirals Immediately" },
  { id: "s45", text: "How well do you handle rejection?", type: "scale", labelLow: "Totally Fine", labelHigh: "It Wrecks Me" },
  { id: "s46", text: "How well do you handle being the center of attention?", type: "scale", labelLow: "Hate It", labelHigh: "Love It" },
  { id: "s47", text: "Rate your current life satisfaction.", type: "scale", labelLow: "Rock Bottom", labelHigh: "Absolutely Thriving" },
  { id: "s48", text: "Rate your middle school experience.", type: "scale", labelLow: "Horrible", labelHigh: "Perfect" },
  { id: "s49", text: "Rate how much you enjoy your own company.", type: "scale", labelLow: "Need People Around", labelHigh: "Love Being Alone" },
  { id: "s50", text: "Rate how well you handle change.", type: "scale", labelLow: "Hate Change", labelHigh: "Thrive On It" },
  { id: "s51", text: "Rate your ability to keep a plant alive.", type: "scale", labelLow: "Serial Killer", labelHigh: "Garden of Eden" },
  { id: "s52", text: "Rate your current sleep schedule.", type: "scale", labelLow: "Completely Broken", labelHigh: "Peak Routine" },
  { id: "s53", text: "Rate your parallel parking ability.", type: "scale", labelLow: "I'd Rather Walk", labelHigh: "First Try Always" },
  { id: "s54", text: "Rate your sense of direction.", type: "scale", labelLow: "Lost Constantly", labelHigh: "Human GPS" },
  { id: "s55", text: "Rate your texting speed.", type: "scale", labelLow: "One Finger", labelHigh: "Lightning Fast" },
  { id: "s56", text: "How emotionally available are you right now?", type: "scale", labelLow: "Closed Off", labelHigh: "Wide Open" },
];

const COWORKERS_PROMPTS: Prompt[] = [
  // Binary
  { id: "cb1",  text: "Are you currently wearing sweatpants under your desk?", type: "binary" },
  { id: "cb2",  text: "Do you listen to music while working?", type: "binary" },
  { id: "cb3",  text: "Have you ever taken a meeting from your bed?", type: "binary" },
  { id: "cb4",  text: "Have you ever eaten someone else's food from the communal fridge?", type: "binary" },
  { id: "cb5",  text: "Do you keep your camera on for every single call?", type: "binary" },
  { id: "cb6",  text: "Have you ever pretended your Wi-Fi cut out to leave a meeting early?", type: "binary" },
  { id: "cb7",  text: "Do you have a designated 'work spot' that you will fight someone for?", type: "binary" },
  { id: "cb8",  text: "Have you ever responded 'Thanks!' to a message that did not require a response?", type: "binary" },
  { id: "cb9",  text: "Do you look at yourself more than the other person during a video call?", type: "binary" },
  { id: "cb10", text: "Have you ever sent a message about someone to the chat that they were currently in?", type: "binary" },
  { id: "cb11", text: "Have you ever nodded along in a meeting when you had absolutely no idea what was being discussed?", type: "binary" },
  { id: "cb12", text: "Do you block out fake focus time on your calendar just to get a break?", type: "binary" },
  { id: "cb13", text: "Have you ever blamed a late deliverable on a 'technical glitch' that didn't exist?", type: "binary" },
  { id: "cb14", text: "Do you clear your browser history at the end of every workday?", type: "binary" },
  { id: "cb15", text: "Have you ever muted a group chat because the notifications were stressing you out?", type: "binary" },

  // Multiple Choice
  { id: "cmc1",  text: "What is your biggest coworking pet peeve?", type: "multiple_choice", options: ["Loud typers", "People taking calls in the open space", "Microwave fish re-heaters", "The person who takes the last coffee and doesn't brew more"] },
  { id: "cmc2",  text: "What is your actual productivity window?", type: "multiple_choice", options: ["5 AM - 9 AM", "9 AM - 12 PM", "2 PM - 5 PM", "11 PM - 2 AM"] },
  { id: "cmc3",  text: "Pick your afternoon slump cure.", type: "multiple_choice", options: ["A third coffee", "An aggressive stretch session", "Scrolling social media for 20 mins", "Staring blankly at a spreadsheet"] },
  { id: "cmc4",  text: "How do your unread notifications look?", type: "multiple_choice", options: ["Inbox Zero always", "A casual 20-50", "Thousands (I use search)", "I have badges turned off"] },
  { id: "cmc5",  text: "What is your primary fuel source?", type: "multiple_choice", options: ["Iced Americano", "Matcha Latte", "Diet Coke / Energy Drinks", "Pure anxiety and water"] },
  { id: "cmc6",  text: "What is your go-to response style on chat?", type: "multiple_choice", options: ["Paragraphs of detailed context", "Strictly emojis and GIFs", "One-word answers (Ack, Done, Cool)", "Leaving people on 'Read' for 4 hours"] },
  { id: "cmc7",  text: "If you could automate one part of your job completely, what would it be?", type: "multiple_choice", options: ["Answering emails/chats", "Filling out timesheets/expense reports", "Sitting through status update meetings", "Building slide decks or spreadsheets"] },
  { id: "cmc8",  text: "What kind of virtual background user are you?", type: "multiple_choice", options: ["The real, unfiltered room", "The standard professional blur", "A tropical beach or space station", "Camera permanently off anyway"] },

  // Would You Rather (2 options)
  { id: "cwyr1", text: "Would you rather have your microphone stuck on mute or your camera stuck on?", type: "multiple_choice", options: ["Microphone stuck on mute", "Camera stuck on"] },
  { id: "cwyr2", text: "Would you rather work from a buzzing café with bad Wi-Fi or a silent room with perfect Wi-Fi?", type: "multiple_choice", options: ["Buzzing café / Bad Wi-Fi", "Silent room / Perfect Wi-Fi"] },
  { id: "cwyr3", text: "Would you rather accidentally reply-all to a company email or message your boss a meme meant for your best friend?", type: "multiple_choice", options: ["Reply-all to company email", "Meme to your boss"] },
  { id: "cwyr4", text: "Would you rather always be 5 minutes late to video calls or 15 minutes early?", type: "multiple_choice", options: ["5 minutes late", "15 minutes early"] },
  { id: "cwyr5", text: "Would you rather work with a giant external monitor but a terrible chair, or a luxury ergonomic chair but just a laptop screen?", type: "multiple_choice", options: ["Great monitor / Bad chair", "Great chair / Laptop screen"] },
  { id: "cwyr6", text: "Would you rather always have your screen shared by accident or always leave your mic unmuted while chewing?", type: "multiple_choice", options: ["Accidental screen share", "Hot mic while chewing"] },
  { id: "cwyr7", text: "Would you rather work a 4-day week with 10-hour days or a 5-day week with 6-hour days?", type: "multiple_choice", options: ["4 days / 10 hours", "5 days / 6 hours"] },

  // Scale
  { id: "cs1", text: "How aggressively do you type when you are stressed?", type: "scale", labelLow: "Feather Touch", labelHigh: "Jackhammer" },
  { id: "cs2", text: "How chaotic is your desktop screen right now?", type: "scale", labelLow: "Pristine", labelHigh: "File_Final_v2.pdf" },
  { id: "cs3", text: "Rate your ability to tolerate small talk at the coffee machine.", type: "scale", labelLow: "Don't Look At Me", labelHigh: "Chief Networker" },
  { id: "cs4", text: "How much of your daily communication is just using emojis?", type: "scale", labelLow: "Strictly Text", labelHigh: "👍🚀🔥 Only" },
  { id: "cs5", text: "Rate your current level of imposter syndrome.", type: "scale", labelLow: "I Built This Place", labelHigh: "They'll Find Out Today" },
  { id: "cs6", text: "How fast do you reply to urgent direct messages?", type: "scale", labelLow: "Sloth Mode", labelHigh: "Instant" },
  { id: "cs7", text: "How much do you actually enjoy team-building icebreakers?", type: "scale", labelLow: "Pure Agony", labelHigh: "Favorite Activity" },
];

const HOTSEAT_PROMPTS: Prompt[] = [
  // Binary
  { id: "pb1",  text: "Have you ever made out with someone in this room?", type: "binary" },
  { id: "pb2",  text: "Have you ever been arrested or held in a cop car?", type: "binary" },
  { id: "pb3",  text: "Have you ever snooped through a host's medicine cabinet or bedroom while visiting?", type: "binary" },
  { id: "pb4",  text: "Have you ever lied to get out of a date while you were actively on the date?", type: "binary" },
  { id: "pb5",  text: "Have you ever gone home with someone purely because their house/apartment was nicer than yours?", type: "binary" },
  { id: "pb6",  text: "Do you have a completely irrational enemy that you actively root against?", type: "binary" },
  { id: "pb7",  text: "Have you ever forgotten the name of someone you were actively hooking up with?", type: "binary" },
  { id: "pb8",  text: "Have you ever successfully talked your way out of a speeding ticket?", type: "binary" },
  { id: "pb9",  text: "Have you ever been kicked out of a bar or venue?", type: "binary" },
  { id: "pb10", text: "If you committed a crime, is there someone in this room who would help you hide the body?", type: "binary" },
  { id: "pb11", text: "Have you ever stalked someone's location on Find My Friends to see if they were lying about their plans?", type: "binary" },
  { id: "pb12", text: "Have you ever eaten food out of a trash can or off the floor (past the 5-second rule)?", type: "binary" },
  { id: "pb13", text: "Have you ever been completely banned from a business, restaurant, or Uber?", type: "binary" },
  { id: "pb14", text: "Do you have a fake social media account strictly used for spying/lurking?", type: "binary" },
  { id: "pb15", text: "Have you ever lied about your birthday at a restaurant just to get free dessert?", type: "binary" },
  { id: "pb16", text: "Have you ever accidentally sent a text complaining about someone *to* that exact person?", type: "binary" },
  { id: "pb17", text: "Have you ever broken a bone doing something incredibly stupid while intoxicated?", type: "binary" },
  { id: "pb18", text: "Have you ever ghosted an event you explicitly promised you would host or help organize?", type: "binary" },
  { id: "pb19", text: "Do you talk to yourself out loud when you are entirely alone?", type: "binary" },
  { id: "pb20", text: "Have you ever gatekept a restaurant, clothing brand, or song because you didn't want it to get 'too popular'?", type: "binary" },

  // Multiple Choice
  { id: "pmc1",  text: "What is your actual red flag when meeting someone new?", type: "multiple_choice", options: ["Too nice", "Phone obsessed", "Friends with exes", "No books"] },
  { id: "pmc2",  text: "Where is the weirdest place you have ever fallen asleep?", type: "multiple_choice", options: ["Public transit", "Bathroom floor", "Concert/Club", "At my desk"] },
  { id: "pmc3",  text: "What's your most chaotic party trick or habit?", type: "multiple_choice", options: ["Irish goodbye", "Bathroom therapist", "Stealing lighters", "Aux cord hijacker"] },
  { id: "pmc4",  text: "How did your last major argument start?", type: "multiple_choice", options: ["Text tone", "Hangry delusion", "Real betrayal", "Dumb hypothetical"] },
  { id: "pmc5",  text: "If you got a call at 3 AM to bail a friend out of jail, what is your reaction?", type: "multiple_choice", options: ["On my way", "Go with insults", "Morning problem", "Do Not Disturb"] },
  { id: "pmc6",  text: "What is your actual criteria for unfriending or unfollowing someone?", type: "multiple_choice", options: ["Gym selfies", "Politics", "Cringe romance", "Random purges"] },
  { id: "pmc7",  text: "What is your biggest minor financial regret?", type: "multiple_choice", options: ["Unused gym", "One-time outfit", "Forgot subscription", "Late-night UberEats"] },
  { id: "pmc8",  text: "You are hosting a party and someone breaks an expensive item. What do you do?", type: "multiple_choice", options: ["Secretly resent them", "Demand Venmo", "Lie to comfort them", "Kick them out"] },
  { id: "pmc9",  text: "What kind of dynamic do you usually bring to a group vacation?", type: "multiple_choice", options: ["Itinerary dictator", "Spreadsheet manager", "2 PM wild card", "Designated parent"] },
  { id: "pmc10", text: "How do you handle a terribly awkward silence in a group?", type: "multiple_choice", options: ["Joke about it", "Look at phone", "Force random topic", "Stare and suffer"] },

  // Would You Rather (2 options)
  { id: "pwyr1",  text: "Would you rather have to tell everyone in this room your exact bank account balance or your last Google search?", type: "multiple_choice", options: ["Bank balance", "Google search"] },
  { id: "pwyr2",  text: "Would you rather accidentally text your mom a screenshot of a conversation talking smack about her, or accidentally text your ex 'I miss you'?", type: "multiple_choice", options: ["Text mom", "Text ex"] },
  { id: "pwyr3",  text: "Would you rather have your worst outfit choice of all time permanently pinned to your social profile, or have your cringiest middle school diary read out loud?", type: "multiple_choice", options: ["Worst outfit pinned", "Diary read aloud"] },
  { id: "pwyr4",  text: "Would you rather deal with a hangover that lasts 2 full days or give up caffeine for a month?", type: "multiple_choice", options: ["2-day hangover", "No caffeine"] },
  { id: "pwyr5",  text: "Would you rather your friends find your secret second social media account, or find your middle school YouTube channel?", type: "multiple_choice", options: ["Secret alt account", "MS YouTube channel"] },
  { id: "pwyr6",  text: "Would you rather have your worst enemy manage your dating profile or your boss manage your financial budget?", type: "multiple_choice", options: ["Enemy manages dating", "Boss manages budget"] },
  { id: "pwyr7",  text: "Would you rather have a permanent, unskippable 30-second ad play in your head every time you wake up, or have to announce your true thoughts out loud once a day?", type: "multiple_choice", options: ["Morning brain ads", "Daily truth reveal"] },
  { id: "pwyr8",  text: "Would you rather always have a wet sock on one foot or have your phone permanently stuck at 8% battery?", type: "multiple_choice", options: ["Wet sock", "8% battery life"] },
  { id: "pwyr9",  text: "Would you rather get a terrible tattoo chosen by the person sitting to your left, or let the person to your right send one text to anyone in your contacts?", type: "multiple_choice", options: ["Tattoo from left", "Text from right"] },
  { id: "pwyr10", text: "Would you rather always talk like a 1920s gangster or always have to dress like a medieval peasant?", type: "multiple_choice", options: ["Gangster voice", "Peasant clothes"] },

  // Scale
  { id: "ps1",  text: "How much of a liability are you after three drinks?", type: "scale", labelLow: "DD Energy", labelHigh: "Needs a Handler" },
  { id: "ps2",  text: "Rate your baseline level of pettiness when someone minorly inconveniences you.", type: "scale", labelLow: "Water Off A Duck", labelHigh: "Plotted Revenge" },
  { id: "ps3",  text: "How much do you actually like the people in this room right now?", type: "scale", labelLow: "Tolerating It", labelHigh: "Obsessed With Them" },
  { id: "ps4",  text: "Rate your ability to fake being completely sober when talking to an authority figure.", type: "scale", labelLow: "Instant Panic", labelHigh: "Oscar Performance" },
  { id: "ps5",  text: "How close are you to throwing your phone into the ocean and moving to a cabin?", type: "scale", labelLow: "Love Modern Life", labelHigh: "Bags Are Packed" },
  { id: "ps6",  text: "How much of a hypochondriac are you when you get a minor headache?", type: "scale", labelLow: "Just Dehydrated", labelHigh: "3 Days To Live" },
  { id: "ps7",  text: "Rate your baseline level of road rage or walking rage (slow walkers).", type: "scale", labelLow: "Zen Master", labelHigh: "Unadulterated Fury" },
  { id: "ps8",  text: "How dramatic is your storytelling style?", type: "scale", labelLow: "Just The Facts", labelHigh: "Full Cinematic Reenactment" },
  { id: "ps9",  text: "Rate your ability to tolerate bad music at a social gathering.", type: "scale", labelLow: "I'll Leave Early", labelHigh: "Vibe To Anything" },
  { id: "ps10", text: "How much do you filter your actual personality depending on who you are talking to?", type: "scale", labelLow: "What You See", labelHigh: "Shape-Shifting Mirror" },
];

export const PROMPTS_BY_BANK: Record<QuestionBank, Prompt[]> = {
  general:   GENERAL_PROMPTS,
  coworkers: COWORKERS_PROMPTS,
  hotseat:   HOTSEAT_PROMPTS,
};

// Legacy export — used by play_again which doesn't carry a bank selection
export const PROMPTS = GENERAL_PROMPTS;

export function getPromptsForGame(n: number, bank: QuestionBank = "general"): Prompt[] {
  const pool = PROMPTS_BY_BANK[bank];
  const shuffled = [...pool];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, Math.min(n, shuffled.length));
}
